builds:
  - binary: h2rzoom
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: h2rzoom
    homepage: https://github.com/alfonsfoubert/h2rzoom
    tap:
      owner: alfonsfoubert
      name: homebrew-alfonsfoubert
    commit_author:
      name: alfonsfoubert
      email: alfonsfoubert@gmail.com

checksum:
  name_template: "checksums.txt"
